import random 

def guess_number(n):
    print('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    print('Welcome !, you should guess the number generated by the computer: ')
    print('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    
    # We generate a random integer
    number_random = random.randint(1, n)

    user_prediction = 0
    
    while user_prediction != number_random:
        user_prediction = int(input(f'Guess a number between 1 and {n}: '))
        
        if user_prediction <= number_random:
            print('Try again. This number is very small')
        elif user_prediction > number_random:
            print('Try again . This number is very big')
    
    print(f'!Congrulations! Guessed the number {number_random} correctly')

guess_number(10)

