import random 

def guess_number(x):
    print('+++++++++++++++++++++++++++++++++++++++')
    print('Welcome !, you should guess the number generated by the computer: ')
    print('+++++++++++++++++++++++++++++++++++++++')
    
    # We generate a random integer
    number_random = random.randint()
    
    

